using System;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Mvc;
using Spoon.Standalone.Connector;

namespace Spoon.Standalone.Example.Controllers
{
    public class HomeController : Controller
    {
        public async Task<ActionResult> Index(string _escaped_fragment_)
        {
            if (_escaped_fragment_ == null)
                return View();

            // NOTE: Failure to respond correctly to _escaped_fragment_ requests could result in your entire site
            // not being indexed. You should at the very least log all errors before handling them appropriately.
            try
            {
                // TODO: Fill in your Azure storage account and storage container names.
                return await SnapshotManager.GetSnapshotAsync(_escaped_fragment_, "", "");
            }
            catch (ArgumentNullException)
            {
                // The _escaped_fragment_ is null. You must verify that it is not null before calling GetSnapshotAsync.
                throw;
            }
            catch (ArgumentException)
            {
                // The Azure storage account name or storage container name is null or whitespace.
                throw;
            }
            catch (HttpRequestException)
            {
                // The _escaped_fragment_ does not correspond to a snapshot generated by Spoon Standalone.
                throw;
            }
            catch
            {
                // If you end up here please create an issue at https://github.com/LeviBotelho/spoon-standalone/issues.
                throw;
            }
        }
    }
}